name: purge-cloudflare-cache
run-name: purge Cloudflare cache
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]

jobs:
  purge-cloudflare-cache:
    environment: cloudflare
    name: purge-cloudflare-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install requests
      - name: Purge Cloudflare cache
        run: python purge-cloudflare-cache.py
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
